name = "teaven-cdn"
main = "src/index.ts"
compatibility_date = "2024-04-03"

[[rules]]
type = "Text"
globs = ["**/*.html"]
fallthrough = true

# R2 配置
[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "morutea-cdn"

# D1 数据库配置
[[d1_databases]]
binding = "DB"
database_name = "cdn-manager"
database_id = "c0ded3ae-f1ac-4cbb-a814-31d8d4637b26"

[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = false
persist = true
head_sampling_rate = 1
